FROM centos
RUN yum -y update
RUN yum -y install openssh-server passwd
RUN useradd anubis && \
    echo anubis:Test*001 | chpasswd && \
    mkdir /home/anubis/.ssh && \
    chmod 700 /home/anubis/.ssh
COPY remote-key.pub /home/anubis/.ssh/authorized_keys
RUN chown remote_user:anubis -R /home/remote_user/.ssh && \
    chmod 600 /home/remote_user/.ssh/authorized_keys
RUN /usr/bin/ssh-keygen -A
CMD /usr/sbin/sshd -D
